v1.1-SNAPSHOT: fix some issues.
In Windows 10, sometimes it will throw:
        javax.sound.midi.MidiUnavailableException: Undefined external error.
like this report described:
        https://bugs.openjdk.java.net/browse/JDK-8159783

When this exception threw, it MUST not continue `player.play()`,
otherwise it will cause java.lang.NullPointerException.

This commit fixed that. (Also makes some functions throw
javax.sound.midi.MidiUnavailableException)